version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
      - /Users/Ugo/dev/compose-press/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: wordpress
       MYSQL_USER: mysql_user
       MYSQL_PASSWORD: mysql_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - /Users/Ugo/dev/compose-press/www:/var/www/html  # Theme development
       - /Users/Ugo/dev/compose-press/themes/:/var/www/html/wp-content/themes
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_USER: mysql_user
       MYSQL_PASSWORD: mysql_password
     ports:
       - 8080:80

volumes:
    db_data:
